version: "2"

services:
  otel_collector:
    depends_on:
      - jaeger
    image: otel/opentelemetry-collector-contrib:0.58.0
    command: --config=/otel_config.yaml
    ports:
      - 4317:4317
    configs:
      - otel_config.yaml
    volumes:
      - ./log.json:/log.json
  jaeger:
    image: jaegertracing/all-in-one:1.37
    environment:
      COLLECTOR_OTLP_ENABLED: true
    expose:
      - 4317:4317
    ports:
      - 16686:16686

configs:
  otel_config.yaml:
    file: ./otel_collector.yaml
